### ISSUE TITLE
Component appears not to be fastboot compatible.

### ISSUE THREAD

**Issue by alexmasita** [trmcnvn/ember-star-rating#10]
This is part of the error I am seeing in the console when I install this addon:

```
There was an error running your app in fastboot. More info about the error:
 Error: Accessing `this.element` is not allowed in non-interactive environments (such as FastBoot).
    at InertRenderer.getElement (/Users/alexmasita/External/Personal/projects/Ember-Apps/mobile-services/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-OkvKfBIB.tmp/assets/ember-glimmer/renderer.js:383:1)
    at Class.get (/Users/alexmasita/External/Personal/projects/Ember-Apps/mobile-services/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-OkvKfBIB.tmp/assets/ember-views/mixins/view_support.js:90:1)
    at Class.exports.default._emberMetal.Mixin.create._Mixin$create.$ (/Users/alexmasita/External/Personal/projects/Ember-Apps/mobile-services/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-OkvKfBIB.tmp/assets/ember-views/mixins/view_support.js:95:1)
```

**Comment by ehubbell** [comment]
@alexmasita @trmcnvn this library still isn't fastboot-compatible. I've submitted PR though that will fix the issue.
